// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyxooavjzwqwjxgjwxaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5eG9vYXZqendxd2p4Z2p3eGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTc5NjQsImV4cCI6MjA2MDI3Mzk2NH0.XrMzGxacYisnIA4jPb_60eND_UkicqK_Iov2D9wkr4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);